### ISSUE TITLE
Use section tag for visual sections instead of div

### ISSUE THREAD

**Issue by heywhahappnd** [AnnaSakivska/sports-app-landing#6]
https://github.com/AnnaSakivska/sports-app-landing/blob/e744ee3756697c5ed5d160611d51322d9e377614/src/index.html#L22-L47
Я выделил только один блок , где следует поменять div на section, чтобы не выделять весь документ. Поменяй пожалуйста все div на section

**Comment by heywhahappnd** [comment]
Не все ведь div на section поменяла

**Comment by AnnaSakivska** [comment]
ні не всі. а потрібно всі? ок, почитаю більше, коли їх використовувати
